### ISSUE TITLE
Error 503 quebec247.org

### ISSUE THREAD

**Issue by pieplu** [savoirfairelinux/quebec-monitoring#3]
http://quebec247.org/ send an error 503 :(

**Comment by matthieucan** [comment]
Hi,
The app was hosted by Savoir-faire Linux, where I don't work anymore. I have no idea if somebody there is up to put it back online.
But if you have access to a server and want to host it I can definitely provide you guidelines :)

**Comment by pieplu** [comment]
Hi!

Now it's back! :)

http://quebec247.org/

**Comment by matthieucan** [comment]
It was offline for a while... No idea what happened!

**Comment by pieplu** [comment]
apparently, only need a serveur restart
